#!/usr/bin/env python3
"""
Obsidian Plugin Generator

Quickly scaffold a new Obsidian plugin with common patterns.

Usage:
    python3 generate_plugin.py <plugin-id> [--path <path>]

Example:
    python3 generate_plugin.py my-awesome-plugin
    python3 generate_plugin.py note-organizer --path /home/user/plugins
"""

import sys
import os
import json
from pathlib import Path
from datetime import datetime

# Templates
MANIFEST_TEMPLATE = """{{
  "id": "{plugin_id}",
  "name": "{plugin_name}",
  "version": "1.0.0",
  "minAppVersion": "0.15.0",
  "description": "{description}",
  "author": "{author}",
  "isDesktopOnly": false
}}
"""

MAIN_TS_TEMPLATE = """import {{ Plugin, Notice, TFile }} from 'obsidian';
import {{ {class_name}Settings, DEFAULT_SETTINGS }} from './settings';
import {{ {class_name}SettingTab }} from './settingsTab';

export default class {class_name} extends Plugin {{
  settings: {class_name}Settings;

  async onload() {{
    await this.loadSettings();

    // Add ribbon icon
    this.addRibbonIcon('dice', '{plugin_name}', (evt: MouseEvent) => {{
      new Notice('{plugin_name} activated!');
    }});

    // Add command
    this.addCommand({{
      id: 'sample-command',
      name: 'Sample Command',
      callback: () => {{
        new Notice('Hello from {plugin_name}!');
      }}
    }});

    // Add settings tab
    this.addSettingTab(new {class_name}SettingTab(this.app, this));

    // Register event
    this.registerEvent(
      this.app.workspace.on('file-open', (file: TFile) => {{
        console.log('Opened:', file?.path);
      }})
    );

    console.log('{plugin_name} loaded');
  }}

  onunload() {{
    console.log('{plugin_name} unloaded');
  }}

  async loadSettings() {{
    this.settings = Object.assign({{}}, DEFAULT_SETTINGS, await this.loadData());
  }}

  async saveSettings() {{
    await this.saveData(this.settings);
  }}
}}
"""

SETTINGS_TS_TEMPLATE = """export interface {class_name}Settings {{
  setting1: string;
  setting2: boolean;
}}

export const DEFAULT_SETTINGS: {class_name}Settings = {{
  setting1: 'default',
  setting2: false
}};
"""

SETTINGS_TAB_TEMPLATE = """import {{ App, PluginSettingTab, Setting }} from 'obsidian';
import {class_name} from './main';

export class {class_name}SettingTab extends PluginSettingTab {{
  plugin: {class_name};

  constructor(app: App, plugin: {class_name}) {{
    super(app, plugin);
    this.plugin = plugin;
  }}

  display(): void {{
    const {{ containerEl }} = this;
    containerEl.empty();

    containerEl.createEl('h2', {{ text: '{plugin_name} Settings' }});

    new Setting(containerEl)
      .setName('Setting 1')
      .setDesc('Description of setting 1')
      .addText(text => text
        .setPlaceholder('Enter value')
        .setValue(this.plugin.settings.setting1)
        .onChange(async (value) => {{
          this.plugin.settings.setting1 = value;
          await this.plugin.saveSettings();
        }}));

    new Setting(containerEl)
      .setName('Setting 2')
      .setDesc('Toggle setting')
      .addToggle(toggle => toggle
        .setValue(this.plugin.settings.setting2)
        .onChange(async (value) => {{
          this.plugin.settings.setting2 = value;
          await this.plugin.saveSettings();
        }}));
  }}
}}
"""

PACKAGE_JSON_TEMPLATE = """{{
  "name": "obsidian-{plugin_id}",
  "version": "1.0.0",
  "description": "{description}",
  "main": "main.js",
  "scripts": {{
    "dev": "node esbuild.config.mjs",
    "build": "tsc -noEmit -skipLibCheck && node esbuild.config.mjs production",
    "version": "node version-bump.mjs && git add manifest.json versions.json"
  }},
  "keywords": ["obsidian", "plugin"],
  "author": "{author}",
  "license": "MIT",
  "devDependencies": {{
    "@types/node": "^16.11.6",
    "builtin-modules": "3.3.0",
    "esbuild": "0.17.3",
    "obsidian": "latest",
    "tslib": "2.4.0",
    "typescript": "4.7.4"
  }}
}}
"""

TSCONFIG_TEMPLATE = """{
  "compilerOptions": {
    "baseUrl": ".",
    "inlineSourceMap": true,
    "inlineSources": true,
    "module": "ESNext",
    "target": "ES6",
    "allowJs": true,
    "noImplicitAny": true,
    "moduleResolution": "node",
    "importHelpers": true,
    "isolatedModules": true,
    "strictNullChecks": true
  },
  "include": ["**/*.ts"]
}
"""

ESBUILD_CONFIG_TEMPLATE = """import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === 'production');

const context = await esbuild.context({
  banner: {
    js: banner,
  },
  entryPoints: ['main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/*',
    'lezer',
    ...builtins],
  format: 'cjs',
  target: 'es2018',
  logLevel: "info",
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
"""

VERSIONS_TEMPLATE = """{{
  "1.0.0": "0.15.0"
}}
"""

VERSION_BUMP_TEMPLATE = """import { readFileSync, writeFileSync } from "fs";

const targetVersion = process.env.npm_package_version;

// read minAppVersion from manifest.json and bump version to target version
let manifest = JSON.parse(readFileSync("manifest.json", "utf8"));
const { minAppVersion } = manifest;
manifest.version = targetVersion;
writeFileSync("manifest.json", JSON.stringify(manifest, null, "\\t"));

// update versions.json with target version and minAppVersion from manifest.json
let versions = JSON.parse(readFileSync("versions.json", "utf8"));
versions[targetVersion] = minAppVersion;
writeFileSync("versions.json", JSON.stringify(versions, null, "\\t"));
"""

GITIGNORE_TEMPLATE = """# Obsidian
*.js
*.js.map
node_modules/
dist/
data.json
.DS_Store
"""


def to_class_name(plugin_id: str) -> str:
    """Convert plugin-id to ClassName"""
    return "".join(word.capitalize() for word in plugin_id.split("-"))


def to_display_name(plugin_id: str) -> str:
    """Convert plugin-id to Display Name"""
    return " ".join(word.capitalize() for word in plugin_id.split("-"))


def generate_plugin(plugin_id: str, output_path: str, author: str, description: str):
    """Generate a complete Obsidian plugin scaffold"""

    plugin_dir = Path(output_path) / plugin_id

    # Check if directory exists
    if plugin_dir.exists():
        print(f"❌ Error: Directory already exists: {plugin_dir}")
        return False

    # Create directory
    plugin_dir.mkdir(parents=True)
    print(f"✅ Created directory: {plugin_dir}")

    class_name = to_class_name(plugin_id)
    plugin_name = to_display_name(plugin_id)

    templates = {
        "manifest.json": MANIFEST_TEMPLATE.format(
            plugin_id=plugin_id,
            plugin_name=plugin_name,
            description=description,
            author=author,
        ),
        "main.ts": MAIN_TS_TEMPLATE.format(
            class_name=class_name, plugin_name=plugin_name
        ),
        "settings.ts": SETTINGS_TS_TEMPLATE.format(class_name=class_name),
        "settingsTab.ts": SETTINGS_TAB_TEMPLATE.format(
            class_name=class_name, plugin_name=plugin_name
        ),
        "package.json": PACKAGE_JSON_TEMPLATE.format(
            plugin_id=plugin_id, description=description, author=author
        ),
        "tsconfig.json": TSCONFIG_TEMPLATE,
        "esbuild.config.mjs": ESBUILD_CONFIG_TEMPLATE,
        "versions.json": VERSIONS_TEMPLATE,
        "version-bump.mjs": VERSION_BUMP_TEMPLATE,
        ".gitignore": GITIGNORE_TEMPLATE,
        "styles.css": f"/* Styles for {plugin_name} */\n",
    }

    # Write all files
    for filename, content in templates.items():
        filepath = plugin_dir / filename
        filepath.write_text(content)
        print(f"✅ Created {filename}")

    # Create README
    readme_content = f"""# {plugin_name}

{description}

## Features

- Feature 1
- Feature 2
- Feature 3

## Installation

1. Download the latest release
2. Extract to your vault's `.obsidian/plugins/` folder
3. Enable the plugin in Obsidian settings

## Development

```bash
npm install
npm run dev
```

## Usage

Describe how to use your plugin here.

## Settings

- **Setting 1**: Description
- **Setting 2**: Description

## License

MIT
"""
    (plugin_dir / "README.md").write_text(readme_content)
    print(f"✅ Created README.md")

    # Create AGENTS.md
    agents_content = f"""# AGENTS

## Project Structure

This is an Obsidian plugin project.

## Development

- Entry point: `main.ts` → compiled to `main.js`
- Build: `npm run dev` (watch) or `npm run build` (production)
- Test: Copy `main.js`, `manifest.json`, and `styles.css` to vault's plugin folder

## Release Checklist

- [ ] Update version in `manifest.json`
- [ ] Update `versions.json`
- [ ] Run `npm run build`
- [ ] Test the plugin
- [ ] Create GitHub release
- [ ] Attach `main.js`, `manifest.json`, `styles.css`
"""
    (plugin_dir / "AGENTS.md").write_text(agents_content)
    print(f"✅ Created AGENTS.md")

    print(f"\n🎉 Plugin '{plugin_name}' generated successfully!")
    print(f"\nNext steps:")
    print(f"  1. cd {plugin_dir}")
    print(f"  2. npm install")
    print(f"  3. npm run dev")
    print(f"  4. Copy main.js and manifest.json to your vault's plugins folder")
    print(f"  5. Enable the plugin in Obsidian settings")

    return True


def main():
    if len(sys.argv) < 2:
        print("Usage: python3 generate_plugin.py <plugin-id> [--path <path>]")
        print("\nExample:")
        print("  python3 generate_plugin.py my-awesome-plugin")
        print("  python3 generate_plugin.py note-organizer --path /home/user/plugins")
        sys.exit(1)

    plugin_id = sys.argv[1]
    output_path = "."

    # Parse arguments
    if "--path" in sys.argv:
        path_index = sys.argv.index("--path")
        if path_index + 1 < len(sys.argv):
            output_path = sys.argv[path_index + 1]

    # Get author from git config or use default
    try:
        import subprocess

        author = (
            subprocess.check_output(["git", "config", "user.name"]).decode().strip()
        )
    except:
        author = "Your Name"

    # Get description
    description = f"A plugin for Obsidian ({plugin_id})"

    print(f"🚀 Generating plugin: {plugin_id}")
    print(f"   Output path: {output_path}")
    print()

    success = generate_plugin(plugin_id, output_path, author, description)
    sys.exit(0 if success else 1)


if __name__ == "__main__":
    main()
